site_name: SSDv2
site_url: https://laster13.github.io/ssdv2_docs/
site_author: ProjetSSD
site_description: >-
  Simple Seedbox Docker

# Repository
repo_name: projetssd/ssdv2
repo_url: https://github.com/projetssd/ssdv2

docs_dir: docs/
exclude_docs: overrides/

# Configuration
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: indigo
      scheme: default
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue grey
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search
  - include-markdown:
      opening_tag: "{!"
      closing_tag: "!}"
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
  - roamlinks
  - mermaid2
  - callouts
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: fr
          default: true
          name: Français
          build: true
        - locale: en
          name: English
          build: true
          theme:
            palette:
              # Palette toggle for light mode
              - media: "(prefers-color-scheme: light)"
                primary: red
                scheme: default
              # Palette toggle for dark mode
              - media: "(prefers-color-scheme: dark)"
                primary: pink
                scheme: slate
          nav_translations:
            Accueil: Home
            Installation: Install
  - git-revision-date-localized:


# Extensions
### Configuration des extensions MarkDown :   
markdown_extensions: # https://squidfunk.github.io/mkdocs-material/reference/abbreviations/
  # extensions de la bibliothèque markdown standard
  - meta                          # Métadonnées
  - def_list                      # Listes de définition.
  - attr_list                     # Sélecteurs CSS et attributs HTML personnalisés
  - footnotes                     # Notes[^1] de bas de page.  [^1]: ma note.
  - admonition                    # Pour permettre les admonitions de MkDocs # Boite d'avertissements  !!! info "ma remarque"
  - toc:                          # Configuration de la table des matières générée automatiquement à partir des titres du niveau 2
        permalink: "&lozf;"          # Ajoute un symbole lien hypertexte vers l'ancre du titre #le-titre 
        toc_depth: 4                # Limite de la profondeur d'inclusion des titres dans la table des matières
  - nl2br                         # Ajoute un retour à la ligne <br> après un saut de ligne simple # A activer pour admonition et si l'option "Sauts de ligne stricts" n'est pas activée dans les réglages de l'éditeur d'Obsidian
  - mdx_breakless_lists           # Permet de commencer une liste sans faire de saut de ligne en amont en ajoutant systématiquement un saut de ligne
  - sane_lists                    # Produit le même affichage de liste qu'Obsidian démarage au nombre indiqué au début d'une liste ordonné : https://python-markdown.github.io/extensions/sane_lists/ 
  - smarty                        # The SmartyPants extension converts ASCII dashes, quotes and ellipses to their HTML entity equivalents https://python-markdown.github.io/extensions/smarty/
  - tables                        # Pour les tableaux https://squidfunk.github.io/mkdocs-material/reference/data-tables/
  # extensions de python-markdown https://facelessuser.github.io/pymdown-extensions/
  - pymdownx.details              # plier/déplier les avertissements - admonition collapsable
  - pymdownx.extra
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret                # texte ^^souligné^^ ou en ^exposant^.
  - pymdownx.mark                 # texte ==surligné==.
  - pymdownx.tilde                # texte ~~barré~~ ou en ~indice~.
  - pymdownx.critic               # Pour du marquage et commentaires de révision de texte
  - pymdownx.magiclink            # Reconnait automatiquement un lien, une adresse à partir de son URL et bien plus : https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/
  - pymdownx.highlight            # Coloration syntaxique du code
  - pymdownx.inlinehilite         # pour  `#!python  <python en ligne>`
  - pymdownx.tasklist:            # Cases à cocher  - [ ]  et - [x]
        custom_checkbox:    true    #   avec cases d'origine
        # clickable_checkbox: true    #   et cliquables.
  - pymdownx.superfences:    # Imbrication de blocs. # pour admonitions MkDocs
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.keys:                # Touches du clavier.  ++ctrl+d++
        separator: "\uff0b"
  - pymdownx.emoji:               # Émojis  :boom:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:          # Formules en LaTeX 
        generic: true
        smart_dollar: false 

# Page tree
nav:
  - Accueil: index.md
  - Installation:
    - Installation/serveur.md
    - Installation/cloudflare.md
    - Installation/domaine.md
    - Installation/installation.md
    - Installation/presentation.md
    - Installation/ajouter-supprimer-reinitialiser.md
    - Installation/manipulations-manuelles.md
    - Utilitaires:
      - Installation/oauth.md
      - Installation/optimisation-cloudflare.md
      - Installation/ufw-Installation-configuration.md
  - RealDebrid:
    - RealDebrid/configuration-rdtclient.md
    - RealDebrid/qbitorrent.md
  - Plex:
    - Plex/Tips/Plex-media-server.md
  - Radarr:
    - Radarr/radarr-setup-quality-profiles-french-fr.md
    - Radarr/radarr-setup-quality-profiles-anime.md
    - Radarr/radarr-setup-quality-profiles.md
    - Radarr/Radarr-remote-path-mapping.md
    - Radarr/Radarr-recommended-naming-scheme.md
    - Radarr/Radarr-Quality-Settings-File-Size.md
    - Radarr/Radarr-import-custom-formats.md
    - Radarr/Radarr-how-to-update-custom-formats.md
    - Tips:
      - Radarr/Tips/Merge-quality.md
      - Radarr/Tips/Sync-2-radarr-sonarr.md
      - Radarr/Tips/How-to-setup-language-custom-formats.md
  - Sonarr:
    - Sonarr/sonarr-setup-quality-profiles-french-en.md
    - Sonarr/sonarr-setup-quality-profiles-anime.md
    - Sonarr/sonarr-setup-quality-profiles.md
    - Sonarr/Sonarr-remote-path-mapping.md
    - Sonarr/Sonarr-Release-Profile-RegEx-Anime.md
    - Sonarr/Sonarr-Release-Profile-RegEx.md
    - Sonarr/Sonarr-recommended-naming-scheme.md
    - Sonarr/Sonarr-Quality-Settings-File-Size.md
    - Sonarr/sonarr-import-custom-formats.md
    - Sonarr/sonarr-how-to-update-custom-formats.md
    - Tips:
      - Sonarr/Tips/Merge-quality.md
      - Sonarr/Tips/Sync-2-radarr-sonarr.md
      - Sonarr/Tips/How-to-setup-language-custom-formats.md
  - Prowlarr:
    - Prowlarr/prowlarr-setup-flaresolverr.md
  - Applications:
    - Applications/Authelia.md
    - Applications/Chevereto.md
    - Applications/Cloudflare.md
    - Applications/Cloudplow.md
    - Applications/Filebot.md
    - Applications/Filerun.md
    - Applications/Grocy.md
    - Applications/Handbrake.md
    - Applications/Jackett---Flaresolverr.md
    - Applications/Medusa.md
    - Applications/Minecraft.md
    - Applications/Nextcloud.md
    - Applications/Ombi.md
    - Applications/Organizr.md
    - Applications/Petio.md
    - Applications/Plex.md
    - Applications/Plex-Dupefinder.md
    - Applications/PlexTratkSync.md
    - Applications/Prestashop.md
    - Applications/Pureftpd.md
    - Applications/QbitorrentVPN.md
    - Applications/Qbittorrent.md
    - Applications/Qflood.md
    - Applications/Rflood.md
    - Applications/Rutorrent.md
    - Applications/Speedtest.md
    - Applications/Traefik.md
    - Applications/Trakt.tv-et-Kitana.md
    - Applications/Traktarr.md
    - Applications/Vikunja.md
    - Applications/watchtower.md
    - Applications/Wordpress.md
    - Applications/Yacht.md
    - Applications/yourls.md

